# Generated by Django 2.2 on 2019-04-26 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('plug', models.IntegerField(default=0)),
                ('cable', models.IntegerField(default=0)),
                ('rosette', models.IntegerField(default=0)),
                ('connector', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_worker', models.BooleanField(default=False)),
                ('surname', models.CharField(default='', max_length=256)),
                ('phone', models.CharField(default='', max_length=16)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Account.Group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ExtUser',
                'verbose_name_plural': 'ExtUsers',
            },
        ),
    ]
