# Generated by Django 2.2 on 2019-04-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('plug', models.IntegerField(default=0)),
                ('cable', models.IntegerField(default=0)),
                ('rosette', models.IntegerField(default=0)),
                ('connector', models.IntegerField(default=0)),
            ],
        ),
    ]
