# Generated by Django 2.2 on 2019-05-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Отряд', 'verbose_name_plural': 'Отряды'},
        ),
    ]
