# Generated by Django 2.2 on 2019-04-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='workers',
        ),
        migrations.AlterField(
            model_name='order',
            name='cable_number',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
