# Generated by Django 2.2 on 2019-05-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20190501_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
