# Generated by Django 2.2 on 2019-04-27 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0002_auto_20190427_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
