# Generated by Django 2.2 on 2019-05-01 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_city_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='default',
            new_name='is_default',
        ),
    ]
