# Generated by Django 2.2 on 2019-04-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_order_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remark',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_type',
            field=models.ManyToManyField(blank=True, null=True, to='Order.WorkType'),
        ),
    ]
