# Generated by Django 2.2 on 2019-05-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20190501_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='apartment',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='Order.City'),
        ),
    ]
