# Generated by Django 2.2 on 2019-05-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20190501_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Типы заявок'},
        ),
        migrations.AlterModelOptions(
            name='usedmaterials',
            options={'verbose_name': 'Использованные материалы', 'verbose_name_plural': 'Использованные материалы'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'Тип работы', 'verbose_name_plural': 'Типы работ'},
        ),
    ]
